name: mirrorme2
version: 0.1.0
author: Joris Hermans <hermansj@gmail.com>
description: A mirrors helper library; adjusted for Dart 2 by Ross Albertson
homepage: https://github.com/rossalbertson/mirrorme2

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
#  unittest: '>=0.9.0 <0.9.1'
  test: ^1.0.0
